### PR TITLE
Enhance swagger: add [401,404,500] responses

### PR DESCRIPTION
**Pull request by bwalsh**
This PR enhances the swagger schema by adding  401,404,500 response values to the expected responses.

### CODE REVIEW

**Comment by tetron** [comment]
I have nothing to add except that I saw the email subject and my first thought was "400 million responses, that seems like a lot?"

**Comment by david4096** [comment]
I'll take @tetron's joke as a tacit +1 ;).

**Comment by bwalsh** [comment]
edited title

**Comment by david4096** [comment]
@bwalsh I included these changes and added a little more in #40 , please take a look there and close this if your satisfied. Thanks!

**Pull request closed without merging**
